/*
@Time : 2020/8/24 18:20
@Author : wangyl
@File : Setting.go
@Software: GoLand
*/
package gobal

import (
	"xing-doraemon/pkg/setting"
	"xing-doraemon/pkg/setting/alterGateway"
)

var alterGatewayConfig alterGateway.AutoGenerated

func GetAlterGatewayConfig() *alterGateway.AutoGenerated {
	return &alterGatewayConfig
}

func InitAlterGatewayConfig(path string) error {
	config, err := setting.NewSetting(path)
	if err != nil {
		return err
	}
	if err := config.ReadStruct(&alterGatewayConfig); err != nil {
		return err
	}
	return nil
}
