/*
@Time : 2020/8/24 18:00
@Author : wangyl
@File : section.go
@Software: GoLand
*/
package setting

type AutoGenerated struct {
	App        App   `json:"App" yaml:"App"`
	Mysql      Mysql `json:"Mysql" yaml:"Mysql"`
	Send       Send  `yaml:"Send"`
	RuleEngine RuleEngine
}
type App struct {
	Httpport  int    `json:"Httpport" yaml:"Httpport"`
	Runmode   string `json:"Runmode" yaml:"Runmode"`
	Sessionon bool   `json:"Sessionon" yaml:"Sessionon"`
}

type Mysql struct {
	DBType    string `json:"DBType" yaml:"DBType"`
	DBUser    string `json:"DBUser" yaml:"DBUser"`
	DBPasswd  string `json:"DBPasswd" yaml:"DBPasswd"`
	DBLoc     string `json:"DBLoc" yaml:"DBLoc"`
	DBConnTTL int    `json:"DBConnTTL" yaml:"DBConnTTL"`
	DBName    string `json:"DBName" yaml:"DBName"`
	DBTns     string `json:"DBTns" yaml:"DBTns"`
}

type Send struct {
	WebHook string `yaml:"WebHook"`
}

type RuleEngine struct {
	NotifyAddr         string
	NotifyPath         string
	NotifyRetries      int
	EvaluationInterval string
	ReloadInterval     string
}
