/*
@Time : 2020/8/24 17:46
@Author : wangyl
@File : setting_test.go.go
@Software: GoLand
*/
package setting

import (
	"fmt"
	"testing"
)

func TestNewSetting(t *testing.T) {
	path := "F:\\GO_svn\\src\\xing-doraemon\\configs\\alterGateway.yml"
	setting, err := NewSetting(path)
	if err != nil {
		t.Fatal(err)
	}
	var result AutoGenerated
	if err = setting.ReadStruct(&result); err != nil {
		t.Fatal(err)
	} else {
		fmt.Println(result)
	}
}
