/*
@Time : 2020/8/24 18:00
@Author : wangyl
@File : section.go
@Software: GoLand
*/
package alterGateway

type AutoGenerated struct {
	Send   Send   `json:"Send" yaml:"Send"`
	Oauth2 Oauth2 `json:"Oauth2" yaml:"Oauth2"`
	Ldap   Ldap   `json:"Ldap" yaml:"Ldap"`
	App    App    `json:"App" yaml:"App"`
	Mysql  Mysql  `json:"Mysql" yaml:"Mysql"`
}
type App struct {
	Appname         string `json:"Appname" yaml:"Appname"`
	Httpport        int    `json:"Httpport" yaml:"Httpport"`
	Runmode         string `json:"Runmode" yaml:"Runmode"`
	Autorender      bool   `json:"Autorender" yaml:"Autorender"`
	Copyrequestbody bool   `json:"Copyrequestbody" yaml:"Copyrequestbody"`
	Sessionon       bool   `json:"Sessionon" yaml:"Sessionon"`
	EnableDocs      bool   `json:"EnableDocs" yaml:"EnableDocs"`
}
type Oauth2 struct {
	TokenUrl     string `json:"TokenUrl" yaml:"TokenUrl"`
	ApiUrl       string `json:"ApiUrl" yaml:"ApiUrl"`
	AuthUrl      string `json:"AuthUrl" yaml:"AuthUrl"`
	ClientId     string `json:"ClientId" yaml:"ClientId"`
	ClientSecret string `json:"ClientSecret" yaml:"ClientSecret"`
}
type Mysql struct {
	DBType    string `json:"DBType" yaml:"DBType"`
	DBUser    string `json:"DBUser" yaml:"DBUser"`
	DBPasswd  string `json:"DBPasswd" yaml:"DBPasswd"`
	DBLoc     string `json:"DBLoc" yaml:"DBLoc"`
	DBConnTTL int    `json:"DBConnTTL" yaml:"DBConnTTL"`
	DBName    string `json:"DBName" yaml:"DBName"`
	DBTns     string `json:"DBTns" yaml:"DBTns"`
}
type Send struct {
	SmsUrl       string `json:"SmsUrl" yaml:"SmsUrl"`
	LanxinUrl    string `json:"LanxinUrl" yaml:"LanxinUrl"`
	CallUrl      string `json:"CallUrl" yaml:"CallUrl"`
	DutyGroupUrl string `json:"DutyGroupUrl" yaml:"DutyGroupUrl"`
	BrokenUrl    string `json:"BrokenUrl" yaml:"BrokenUrl"`
	WebUrl       string `json:"WebUrl" yaml:"WebUrl"`
}
type Ldap struct {
	LdapSearchDn          string `json:"LdapSearchDn" yaml:"LdapSearchDn"`
	LdapSearchPassword    string `json:"LdapSearchPassword" yaml:"LdapSearchPassword"`
	LdapUid               string `json:"LdapUid" yaml:"LdapUid"`
	LdapScope             int    `json:"LdapScope" yaml:"LdapScope"`
	LdapUrl               string `json:"LdapUrl" yaml:"Ldap_url"`
	LdapBaseDn            string `json:"LdapBaseDn" yaml:"LdapBaseDn"`
	LdapFilter            string `json:"LdapFilter" yaml:"LdapFilter"`
	LdapConnectionTimeout int    `json:"LdapConnectionTimeout" yaml:"LdapConnectionTimeout"`
	Enabled               bool   `json:"Enabled" yaml:"Enabled"`
}
