App:
  Httpport: 8080
  Runmode: "dev"
  Sessionon: true

Mysql:
  DBType : "mysql"
  DBName: "doraemon"
  DBTns: "49.234.224.9:3306"
  DBUser: "root"
  DBPasswd: "root"
  DBLoc: "Asia%2FShanghai"
  DBConnTTL: 5

Send:
  WebHook: ''
