App:
  Httpport: 8080
  Runmode: "dev"
  Sessionon: true

Mysql:
  DBType : "mysql"
  DBName: "doraemon"
  DBTns: "localhost:3306"
  DBUser: "root"
  DBPasswd: "123456"
  DBLoc: "Asia%2FShanghai"
  DBConnTTL: 5

Send:
  WebHook: ''

RuleEngine:
  NotifyRetries: 3
  EvaluationInterval: '15s'
  ReloadInterval: '5m'
