definitions:
  Resp.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  view.ConfirmAlertsReq:
    properties:
      alert_list:
        items:
          type: integer
        type: array
    type: object
  view.CreatePlanReq:
    properties:
      end_time:
        type: string
      expression:
        type: string
      name:
        type: string
      period:
        type: integer
      start_time:
        type: string
    required:
    - period
    type: object
  view.CreateProm:
    properties:
      name:
        type: string
      url:
        type: string
    required:
    - name
    - url
    type: object
  view.CreateRuleReq:
    properties:
      description:
        type: string
      expr:
        type: string
      for:
        description: 持续时间，单位秒
        type: integer
      op:
        type: string
      plan_name:
        type: string
      prom_name:
        type: string
      summary:
        type: string
      value:
        type: string
    type: object
  view.DeleteProm:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  view.DeleteRuleReq:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  view.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  view.ModifyPlanReq:
    properties:
      end_time:
        type: string
      expression:
        type: string
      id:
        type: integer
      name:
        type: string
      period:
        type: integer
      start_time:
        type: string
    required:
    - id
    type: object
  view.ModifyProm:
    properties:
      id:
        type: integer
      name:
        type: string
      url:
        type: string
    required:
    - id
    type: object
  view.ModifyRuleReq:
    properties:
      description:
        type: string
      expr:
        type: string
      for:
        type: integer
      id:
        type: integer
      op:
        type: string
      plan_name:
        type: string
      prom_name:
        type: string
      summary:
        type: string
      value:
        type: string
    type: object
  view.UserCreateReq:
    properties:
      password:
        type: string
      user_name:
        type: string
    type: object
  view.UserDeleteReq:
    properties:
      id:
        type: integer
    type: object
  view.UserUpdateReq:
    properties:
      id:
        type: integer
      password:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
  license: {}
  title: prometheus Alert management center
  version: "2.0"
paths:
  /api/v1/alerts:
    get:
      parameters:
      - description: 页号
        in: query
        name: page
        required: true
        type: integer
      - description: 页大小
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 获取告警列表
  /api/v1/alerts/confirm:
    get:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.ConfirmAlertsReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 告警确认
  /api/v1/plan:
    delete:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.DeleteRuleReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 删除plan
    get:
      parameters:
      - description: 页序号
        in: query
        name: page
        required: true
        type: string
      - description: 页大小
        in: query
        name: page_size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 获取Plan列表，分页
    post:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.CreatePlanReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 创建plan
    put:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.ModifyPlanReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 修改plan
  /api/v1/plan/allNames:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 获取所有prom名
  /api/v1/planID:
    get:
      parameters:
      - description: 序号
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 获取单个Plan
  /api/v1/prom:
    delete:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.DeleteProm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 删除prom
    get:
      parameters:
      - description: 页序号
        in: query
        name: page
        required: true
        type: string
      - description: 页大小
        in: query
        name: page_size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 获取proms, 分页
    post:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.CreateProm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 创建prom
    put:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.ModifyProm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 修改prom
  /api/v1/prom/allName:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 获取所有prom名
  /api/v1/promId:
    get:
      parameters:
      - description: 页序号
        in: query
        name: Id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 获取单个prom
  /api/v1/rule:
    delete:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.DeleteRuleReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 删除rule
    get:
      parameters:
      - description: 序号
        in: query
        name: page
        required: true
        type: string
      - description: 序号
        in: query
        name: page_size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 获取rules列表，分页
    post:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 用户登录
    put:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.ModifyRuleReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 修改rule
  /api/v1/ruleId:
    get:
      parameters:
      - description: 序号
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 获取单个rule
  /api/v1/user/create:
    post:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.UserCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 添加用户
  /api/v1/user/delete:
    delete:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.UserDeleteReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 修改用户
  /api/v1/user/list:
    get:
      parameters:
      - description: 序号
        in: query
        name: page
        required: true
        type: string
      - description: 序号
        in: query
        name: page_size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 用户列表
  /api/v1/user/update:
    put:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/view.UserUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Resp.Response'
      summary: 修改用户
swagger: "2.0"
